Pantaris integration
eclipse-velocitas/devenv-runtimes pull request #39
Opened 2023-09-01 06:59 UTC by MP91

2023-09-12 12:25 UTC, doosuu requested changes
Can you add an integration test?

2023-09-12 12:25 UTC, doosuu commented on .devcontainer/scripts/post-create.sh
> +pip3 install --upgrade pip
Why 2x upgrade pip?

2023-09-12 12:25 UTC, doosuu commented on .devcontainer/scripts/post-create.sh
> +REQUIREMENTS="runtime_k3d/src/requirements.txt"
Could we introduce a list of components and iterate over them? [ runtime_k3d, runtime_kanto, runtime_local ] ...

2023-09-12 12:25 UTC, doosuu commented on README.md
> +## Generators
```suggestion
## Deployment spec generators
```

2023-09-12 12:25 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +def is_uri(path: str) -> bool:
Candidate to move to velocitas_lib

2023-09-12 12:25 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +    """Parses the vehicle signal interface config.
Should be imperative, pydocstyle should complain.

```suggestion
    """Parse the vehicle signal interface config.
```

2023-09-12 12:25 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +        requirements.append(f"vss-source-default-vss:{version}")
`"vss-source-default"` and other identifiers should be constants.

2023-09-12 12:25 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +    """Parses the grpc interface config.
Should be imperative, pydocstyle should complain.
```suggestion
    """Parse the grpc interface config.
```

2023-09-12 12:25 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +    """Parses the defined interfaces.
Should be imperative, pydocstyle should complain.
```suggestion
    """Parse the defined interfaces.
```

2023-09-12 12:25 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +def get_md5_from_uri(src: str) -> str:
function name suggests it generates the hash of the URI string, not the hash of the contents of the downloaded file.

Maybe call this `generate_hash_from_file_contents(uri)` where `uri` might be a local file or a remote file.

2023-09-12 12:25 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +def get_package_version(package_id: str) -> str:
Why is this called `get_package_version` when it returns the version of the MQTT broker?

2023-09-12 12:25 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +    parser = argparse.ArgumentParser("generate-desired-state")
Suggestion: Make `main` the main entry point which is not accepting arguments via commandline but as real python arguments. That way you can test your `main` without writing to/mocking stdin. Only `if __name__ == "__main__"`: should do the argument parsing and pass the arguments to main.

2023-09-12 12:25 UTC, doosuu commented on desired_state_generator/src/requirements.txt
> +requests==2.31.0
`velocitas_lib` provides `download_file` and already has a dependency to `requests`, can you re-use that function?

2023-09-12 12:25 UTC, doosuu commented on manifest.json
> +            "type": "generator",
There is no type `generator`. At the moment we support `setup`, `runtime` and `deployment` as can be seen here: https://github.com/eclipse-velocitas/cli/blob/main/src/modules/component.ts#L42

This is really bad and superseded already and will be removed by this PR on the CLI: https://github.com/eclipse-velocitas/cli/pull/150

Nevertheless, we do not want to wait with your PR until the CLI PR is released. For now I would suggest to use the most commonly used type here: `setup`.

2023-09-12 12:25 UTC, doosuu commented on desired_state_generator/src/install_deps.py
File can be removed, it does not do anything else than invoking pip. This can be modelled in the manifest.json already.

2023-09-12 12:25 UTC, doosuu commented on manifest.json
> +                        "./desired_state_generator/src/install_deps.py"
Sufficient to use 
```suggestion
                        "-m", "pip", "-r", "./desired_state_generator/src/requirements.txt"
```

2023-09-12 12:25 UTC, doosuu commented on manifest.json
> +            "variables": [
None of these variables is used in desired-state-generator, hence you can remove these definitions from here. Variable list can be empty.

2023-09-12 12:25 UTC, doosuu commented on runtime_k3d/src/install_deps.py
>      install_packages()
File can be removed, manifest.json can directly invoke pip, see previous comment.

2023-09-12 12:25 UTC, doosuu commented on runtime_k3d/test/requirements.txt
Do we really need the dependency here? The main src should already have this as a dependency.

2023-09-12 12:25 UTC, doosuu commented on runtime_kanto/src/install_deps.py
File not needed, can be done directly in mainfest.json by invoking pip directly.

2023-09-12 12:25 UTC, doosuu commented on runtime_local/src/install_deps.py
File not needed, can be done directly in manfest.json by invoking pip.

2023-09-12 12:25 UTC, doosuu commented on setup.cfg
> +ignore_missing_imports = True
Really needed?

2023-09-12 12:25 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +        config: The json-config of the interface, as defined in the appManifest.json.
Missing type for config. Try using VSCode pydoc auto-comment extension.

2023-09-13 05:43 UTC, MP91 commented on desired_state_generator/src/gen_desired_state.py
> +def is_uri(path: str) -> bool:
definitely but the sake of time I would like to keep it here for now. There are also some other methods which we could move.

2023-09-13 05:43 UTC, MP91 commented on .devcontainer/scripts/post-create.sh
> +pip3 install --upgrade pip
copy`n`paste error -> fixed

2023-09-13 06:35 UTC, MP91 commented on manifest.json
> +            "variables": [
I really would like to, but the velocitas_lib needs them in some functions...

2023-09-13 07:00 UTC, MP91 commented on runtime_k3d/test/requirements.txt
in ci we only install the test-requirements, that's why it is needed here...

2023-09-13 07:08 UTC, MP91 commented on desired_state_generator/src/gen_desired_state.py
> +def is_uri(path: str) -> bool:
also the md5 hashing can be moved there

2023-09-13 07:10 UTC, MP91 commented on setup.cfg
> +ignore_missing_imports = True
mypy is otherwise complaining about the velocitas_lib...

2023-09-14 06:57 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +        file_path = "./tmp"
better use `tempfile.TemporaryDirectory` which will auto remove the directory and its contents once the object is cleaned up.

2023-09-14 11:53 UTC, doosuu requested changes

2023-09-14 11:53 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +VSS_SOURCE_DEFAULT = "vss-source-default-vss"
```suggestion
VSS_SOURCE_DEFAULT = "vss-source-default"
```

2023-09-14 11:53 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +VSS_SOURCE_CUSTOM = "vss-source-custom-vss"
```suggestion
VSS_SOURCE_CUSTOM = "vss-source-custom"
```

2023-09-14 11:53 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +GRPC_INTERFACE_ID = "dataprovider-proto-grpc"
```suggestion
GRPC_INTERFACE_ID = "grpc-interface"
```

2023-09-14 11:53 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +DATABROKER_PACKAGE_ID = "vehicledatabroker"
Unused?

2023-09-14 11:53 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +MQTT_PACKAGE_ID = "mqtt-broker"
Unused?

2023-09-14 11:53 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +VSS_INTERFACE = "vehicle-signal-interface"
We should prefix these constants so we know which are used in which context:

```suggestion
VELOCITAS_IF_TYPE_VSI = "vehicle-signal-interface"
```

2023-09-14 11:53 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +PUBSUB_INTERFACE = "pubsub"
```suggestion
VELOCITAS_IF_PUBSUB = "pubsub"
```

2023-09-14 11:53 UTC, doosuu commented on desired_state_generator/src/gen_desired_state.py
> +GRPC_INTERFACE = "grpc-interface"
```suggestion
VELOCITAS_IF_GRPC = "grpc-interface"
```

2023-09-14 12:41 UTC, doosuu approved these changes
LGTM

2023-09-14 12:42 UTC, merged